# Generated by Django 4.2.6 on 2024-01-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worky', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(height_field=400, upload_to='worky/media', width_field=600),
        ),
    ]
