# Generated by Django 5.0 on 2024-02-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worky", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="time",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.CharField(max_length=200),
        ),
    ]
