# Generated by Django 4.2.6 on 2024-01-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worky', '0002_alter_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(upload_to='img/%y'),
        ),
    ]
