# Generated by Django 4.2.3 on 2023-09-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worky', '0002_remove_feedback_name_remove_message_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='time',
            field=models.DateTimeField(default='2023-09-22 18:08:06.054505'),
        ),
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default='2023-09-22 18:08:06.054505'),
        ),
    ]
